import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import SideNav from '@/components/custom/SideNav';
import { Nunito } from 'next/font/google';
import Nav from '@/components/custom/Nav';
import 'react-toastify/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

const nunito = Nunito({
    subsets: ['latin'],
    variable: '--font-nunito',
    display: 'swap',
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${nunito.className}`}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased text-slate-800  min-h-screen min-w-screen bg-slate-100 relative`}
            >
                <ToastContainer />
                <header>
                    <Nav />
                </header>
                <main className="flex">
                    <div className="hidden lg:block fixed left-0 top-0 bottom-0 w-64 bg-white shadow-md">
                        <SideNav />
                    </div>
                    <div className="w-full lg:pl-64">{children}</div>
                </main>
            </body>
        </html>
    );
}
